// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartialActionGenerator } from "./PartialActionGenerator";

export type Actions = { shortcuts: { [key in string]?: PartialActionGenerator }, palettes: { [key in string]?: { [key in string]?: PartialActionGenerator } }, };
