// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodeResult = { "type": "ok", text: string, } | { "type": "error", message: string, };
