// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandPaletteType } from "./CommandPaletteType";
import type { Insertion } from "./Insertion";
import type { Locater } from "./Locater";

export type CommandAction = { "type": "Goto", target: Locater, new_window: boolean, } | { "type": "Subcommand", subcommand: CommandPaletteType, } | { "type": "AddPinned", insertion: Insertion, path: string, } | { "type": "RemovePinned" } | { "type": "EditTitle" } | { "type": "SaveWindowState" } | { "type": "SaveNote" } | { "type": "ToggleNoteMinimized" } | { "type": "Refresh" };
