// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GotoTarget } from "./GotoTarget";
import type { Insertion } from "./Insertion";
import type { Subcommand } from "./Subcommand";

export type CommandAction = { "type": "Goto", target: GotoTarget, new_window: boolean, } | { "type": "Subcommand", subcommand: Subcommand, } | { "type": "AddPinned", insertion: Insertion, path: string, } | { "type": "RemovePinned" } | { "type": "EditTitle" };
