// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorState } from "./EditorState";
import type { PinnedEditorState } from "./PinnedEditorState";

export type EditorStates = { pinned: { [key in string]?: PinnedEditorState }, notes: { [key in string]?: EditorState }, };
