// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Locater = { "type": "Note", path: string, } | { "type": "Pinned", focus_path: string | null, } | { "type": "Settings" } | { "type": "New" };
