// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteAction } from "./PaletteAction";

export type MatchedPaletteAction = { indices: Array<number>, paletteAction: PaletteAction, };
