// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartialAction } from "./PartialAction";

export type PaletteAction = { title: string, icon: string | null, action: PartialAction, };
