// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorState } from "./EditorState";

export type PinnedEditorState = { folded: boolean, note_state: EditorState, };
