// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Command } from "./Command";
import type { Note } from "./Note";
import type { Settings } from "./Settings";

export type ServerMessage = { "type": "Settings", settings: Settings, } | { "type": "Note", note: Note | null, } | { "type": "NotePath", path: string, } | { "type": "None" } | { "type": "Commands", commands: Array<Command>, } | { "type": "Pinned", pinned: Array<string>, } | { "type": "Error", error: string, };
