// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerMessage } from "./ServerMessage";

export type ServerResult = { "type": "ok", message: ServerMessage, } | { "type": "err", error: string, };
