// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locater } from "./Locater";
import type { WindowState } from "./WindowState";

export type Settings = { notes_path: string | null, window_states: { [key in Locater]?: WindowState }, minimized_pinned_paths?: Array<string>, };
