// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locater } from "./Locater";
import type { WindowState } from "./WindowState";

export type Settings = { notesPath: string | null, windowStates: { [key in Locater]?: WindowState }, minimizedPinnedPaths?: Array<string>, };
