// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utf16Index } from "./Utf16Index";

export type SourceChange = { "Replace": string } | { "Edits": Array<[{ start: Utf16Index, end: Utf16Index, }, string]> };
