// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Insertion } from "./Insertion";

export type Subcommand = { "type": "AddPinned", insertion: Insertion, };
