// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowState = { width: number, height: number, x: number, y: number, floating: boolean, };
